// Code generated by sqlc. DO NOT EDIT.
// source: song.sql

package db

import (
	"context"
)

const getSong = `-- name: GetSong :one
SELECT id, name
FROM songs
WHERE id = $1
`

type GetSongRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetSong(ctx context.Context, id int32) (GetSongRow, error) {
	row := q.db.QueryRowContext(ctx, getSong, id)
	var i GetSongRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, name, labels
FROM songs
ORDER BY id
`

func (q *Queries) ListSongs(ctx context.Context) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(&i.ID, &i.Name, &i.Labels); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
